extension_dir="C:\Users\magene\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe\ext"
extension=openssl
extension=curl
extension=fileinfo
extension=gd
extension=mbstring
extension=pdo_mysql
extension=mysqli
extension=pdo_sqlite
extension=sqlite3
extension=zip
date.timezone=Asia/Jerusalem
memory_limit=512M
max_execution_time=180
upload_max_filesize=25M
post_max_size=30M
max_file_uploads=50
